const towns = [
  "Ahumada",
  "Aldama",
  "Balleza",
  "Camargo",
  "Chihuahua",
  "Cuauhtémoc",
  "Delicias",
  "Jiménez",
  "Juárez",
  "Hidalgo del Parral",
  "Aquiles Serdán",
  "Ascensión",
  "Bachíniva",
  "Batopilas de Manuel Gómez Morín",
  "Bocoyna",
  "Buenaventura",
  "Carichí",
  "Casas Grandes",
  "Coronado",
  "Coyame del Sotol",
  "La Cruz",
  "Cusihuiriachi",
  "Chínipas",
  "Dr. Belisario Domínguez",
  "Galeana",
  "Santa Isabel",
  "Gómez Farías",
  "Gran Morelos",
  "Guachochi",
  "Guadalupe y Calvo",
  "Guazapares",
  "Guerrero",
  "Huejotitán",
  "Ignacio Zaragoza",
  "Janos",
  "Julimes",
  "López",
  "Madera",
  "Maguarichi",
  "Manuel Benavides",
  "Matachí",
  "Matamoros",
  "Meoqui",
  "Morelos",
  "Moris",
  "Namiquipa",
  "Nonoava",
  "Nuevo Casas Grandes",
  "Ocampo",
  "Ojinaga",
  "Praxedis G. Guerrero",
  "Riva Palacio",
  "Rosales",
  "Rosaeio",
  "San Francisco de Borja",
  "San Francisco de Conchos",
  "San Francisco del Oro",
  "Santa Bárbara",
  "Satevó",
  "Saucillo",
  "Temósachic",
  "El Tule",
  "Urique",
  "Urique",
  "Valle de Zaragoza"
];

export default towns;
